### ISSUE TITLE
Typos and such in README.md

### ISSUE THREAD

**Issue by hepabolu** [bbusschots-mu/validateParams.js#14]
In this part:

> Validate.js is designed to valid web forms. HTML form data is fundamentally a collection of name-value pairs, so it makes sense that the validation functions provided by valiate.js expect both the data to be validated, and the constraints to be applied to that data to be specified as collections of name-value pairs (JavaScript objects).

... provided by valiate.js.... should be 
... provided by validate.js....

Also, the last two sentences above the Installation paragraph don't make sense and don't start with a capital.

**Comment by bbusschots-mu** [comment]
Fixed with fb244ff8a9a3daf5a4b67100065d600d7a7c426c
